import express from "express";
const app = express();
import Lab5 from "./Lab5/index.js";
import Hello from "./Hello.js";
import cors from "cors";
app.use(cors());
Lab5(app);
app.use(express.json());
Hello(app);
app.listen(process.env.PORT || 4000);
